# Generated by Django 4.0 on 2022-01-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='test',
        ),
    ]
